# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
# FROM tiangolo/node-frontend:10 as build-stage
FROM node:12-alpine as build-stage

WORKDIR /app

COPY package*.json /app/
RUN npm install

RUN npx next telemetry disable

COPY ./ ./next.config.js /app/
RUN npm run build

EXPOSE 3000
CMD [ "npm", "start" ]

