# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
# FROM tiangolo/node-frontend:10 as build-stage
FROM node:12-alpine as build-stage

WORKDIR /app

COPY package*.json tsconfig.json /app/
RUN npm install

RUN npx next telemetry disable

COPY ./ ./next.config.js ./firebase-config-gcp.json /app/
COPY ./.env.production /app/
RUN npm run build

EXPOSE 3000
ENV NODE_ENV "production"
ENV PORT 3000

CMD [ "npm", "run", "start:dev" ]

