export const Theme =  {
    dwelling : 'Om Boligen',
    ownerExpedenaturesEconomy : 'Bolig: Eieforhold og økonomi',
    mortgage: 'Boliglån',
    rentDwelling: 'Utgifter til husleie',
    municipalExpenditure: 'Kommunale avgifter',
    powerDwelling: 'Bolig: Elektristitet og oppvarming',
    powerHolidayHome: 'Fritidsbolig i Norge: Elektrisitet og brensel',
    garageExpendatures: 'Utgifter til garasje',
    renovationDwelling: 'Bolig: Oppgradering eller vedlikehold',
    insuranceDwelling: 'Boligforsikring',
    holidayHome: 'Fritidsbolig i Norge',
    holidayHomeAbroad: 'Fritidsbolig i utlandet',
    renovationHolidayHome: 'Fritidsbolig i Norge: Oppgradering og vedlikehold',
    insuranceHolidayHome: 'Boligforsikring fritidsbolig',
    firewood: 'Egenproduksjon av ved',
    carPurchase: "Bilkjøp",
    car: 'Bil',
    travels: 'Reiser',
    education: 'Skole og utdanning',
    rarePurchases: 'Sjeldne kjøp (av varig verdi)',
    insuranceCost: 'Forsikingsutgifter'
}